2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:26 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:30 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:30 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:30 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:48 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:19:51 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:20:08 | ERROR | CWReceiver: No internet connection.
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29851 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491b890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=33682 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491ae90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29498 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734918910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=36766 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734918550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=31093 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=30688 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734919590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29720 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349187d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=28387 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734919310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=28386 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734918050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=30634 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734918690>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=28375 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a8f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=33423 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a8cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:23:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=37208 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a8910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:03 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a8410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=35927 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491ae90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29725 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491bed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=30080 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734919810>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=36769 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491b9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=30642 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491b390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:16 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29373 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5734919450>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:20 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29658 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a87d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:20 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=31049 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a8550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:20 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=37214 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a9090>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:24:37 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=33711 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349196d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:25:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29851 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f573491a5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:25:55 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=31093 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349aa350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:25:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=30688 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a9bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:25:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=28387 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349a9f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:25:59 | ERROR | CWReceiver: No internet connection. HTTPSConnectionPool(host='ks.innov.cleanwatts.energy', port=443): Max retries exceeded with url: /api/2.0/data/lastvalue/Instant?from=2003-06-11&tags=29660 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57349aa210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-21 16:26:27 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:27:10 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:28:54 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:29:54 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:30:53 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:31:54 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:32:57 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:33:57 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:34:53 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-21 16:35:53 | WARNING | CWReceiver: Error getting data from tag 30688: 404
2025-02-25 16:04:13 | WARNING | CWReceiver: Error getting data from tag 30688: 404
